
CREATE SCHEMA CRAWL;
COMMIT;

CREATE TABLE CRAWL.PERSON (
  NAME            VARCHAR(50),
  ALIAS           VARCHAR(50),
  ENGLISHNAME     VARCHAR(50),
  GENDER          CHAR(1),
  BIRTHDAY        DATE,
  AGE             INTEGER,
  HOMETOWN        VARCHAR(100),
  TAG             TEXT[],
  AUDITUSER       VARCHAR(50),
  AUDITDATE       DATE,
  CREATOR         VARCHAR(50),
  CREATEDATE      DATE,
  LASTMODIFYDATE  DATE,
  MODIFIER        VARCHAR(50),
  SOURCEURL       TEXT
)
WITH OIDS;
ALTER TABLE CRAWL.PERSON ADD PRIMARY KEY (OID);
COMMIT;

CREATE TABLE CRAWL.ORGANIZATION (
  ORGANIZATIONNAME       TEXT,
  ALIAS                 TEXT,
  TYPEID                INTEGER,
  REGLOC                TEXT,
  REGDATE               DATE,
  ENDDATE               DATE,
  TAG                   TEXT[],
  IPOCODE               VARCHAR(50),
  IPODATE               DATE,
  REMARK                VARCHAR(50),
  CREATOR               VARCHAR(50),
  CREATEDATE            DATE,
  LASTMODIFYDATE        DATE,
  MODIFIER              VARCHAR(50),
  AUDITUSER             VARCHAR(50),
  AUDITDATE             DATE
)
WITH OIDS;
ALTER TABLE CRAWL.ORGANIZATION ADD PRIMARY KEY (OID);
COMMIT;

CREATE TABLE CRAWL.EMPLOYMENT (
  PERSONID        INTEGER,
  ORGANIZATIONID  INTEGER,
  STARTDATE       DATE,
  ENDDATE         DATE,
  LOCATION        DATE,
  POSITION        VARCHAR(50),
  TAG             TEXT[],
  CREATOR         VARCHAR(50),
  CREATEDATE      DATE,
  LASTMODIFYDATE  DATE,
  MODIFIER        VARCHAR(50),
  AUDITUSER       VARCHAR(50),
  AUDITDATE       DATE
)
WITH OIDS;
ALTER TABLE CRAWL.EMPLOYMENT ADD PRIMARY KEY (OID);
ALTER TABLE CRAWL.EMPLOYMENT ADD FOREIGN KEY (OID) REFERENCES CRAWL.PERSON(OID);
ALTER TABLE CRAWL.EMPLOYMENT ADD FOREIGN KEY (ORGANIZATIONID) REFERENCES CRAWL.ORGANIZATION(OID);
COMMIT;

CREATE TABLE CRAWL.TEST (
  NAME  TEXT,
  ROLE  VARCHAR(2)
)
WITH OIDS;
ALTER TABLE CRAWL.TEST ADD PRIMARY KEY(OID);
